### ISSUE TITLE
config link is not always available in 6.3.4.1

### ISSUE THREAD

**Issue by nopzdk** [pfpayments/shopware-6#1]
when i activate the plugin the config is available, but if I leave the page and come back then it is no longer available and i have to deactivate/activate to get the option to enter the config menu.
i did not enter the config menu straight away.
only after i added the credentials the other config menu appeared.

also the command composer require postfinancecheckout/shopware-6 does not find the plugin, i had to do a manual install.

**Comment by vttn** [comment]
@nopzdk 

We added the repo to packagist, it should now be available via composer.

As for the config menu, this is on Shopware 6. We show the menu according to Shopware 6 guidelines.

Regards,

@vttn
