### ISSUE TITLE
Installation viel zu kompliziert

### ISSUE THREAD

**Issue by godoffrags** [pfpayments/shopware-6#2]
Hi,

Die installation ist viel zu komplziert.
Beide installationen sind composer abhängig.
Ein Otto normal Nutzer hat keinen Shell zugang geschweige denn zugriff auf Composer oder das knowhow.
Composer ist auch bei einem normalen hosting nicht immer installiert.

Für eine installation müssen wir derzeit das Plugin auf einem anderen Server hochladen wo wir composer haben.
Dort die Composer json anpassen und die Shopware abhängigkeiten raus löschen. Weil wir da kein Shopware haben.
Dann composer install ausführen. Eine Zip Datei erstellen aus den Ordnern/Dateien die man direkt im Admin von shopware hochladen kann. Viel zu umständlich. Mit ein paar kniffen für Ihren Release könnte das Plugin direkt im Admin hochgeladen werden.

Bitte ein Release raus bringen den man direkt im Shopware Admin hochladen kann auf der Plugin Seite.
In diesem Release sollten auch gleich die nötigen Bibliotheken (Composer "vendor" Ordner) integriert sein.
Sie können diesen ja mit einem neuen release auch gleich updaten. Falls sich die Bibiliotheken aktualisiert haben.
Damit der Upload klappt muss nur noch der Ordner und die Zipdatei den korrekten namen haben.
Ordner Struktur innerhalb der Zip Datei PostFinanceCheckoutPayment.zip
- PostFinanceCheckoutPayment
-  - docs
- -  src
- -  vendor
- -  composer.json
- -  ...

Dann kann man es endlich ganz simple im Admin hochladen.

Gruß Christian

**Comment by theodorspringwallee** [comment]
Guten Tag [godoffrags](https://github.com/godoffrags)

Bitte entschuldigen Sie die späte Antwort.

Das Plugin ist mittlerweile im Shopware 6 Marketplace verfügbar: https://store.shopware.com/en/postf12988642377f/postfinance-checkout-shopware-6.html 

Daher denke ich, dass sich dieses Problem mittlerweile gelöst hat.

Freundliche Grüsse
