### ISSUE TITLE
Plugin Einstellungen nicht mehr sichtbar

### ISSUE THREAD

**Issue by diickens** [pfpayments/shopware-6#4]
Seit dem letzten Update auf Version: 4.0.44 sehe ich leider unter Einstellungen -> Erweiterungen keine "Postfinance Checkout" option mehr. Das Plugin und Postfinance Checkout Flex ist für mich momentan so unbrauchbar. 

Gibts da ein Fix?

Beste Grüsse

**Comment by theodorspringwallee** [comment]
Hallo

Bitte entschuldigen Sie die späte Rückmeldung.

Das genannte Problem können wir in unseren Testsystemen nicht reproduzieren.

Daher bitten wir Sie direkt den PostFinanceCheckout Support zu kontaktieren: https://www.postfinance.ch/de/support/hotline.html

Beste Grüsse

**Comment by outamaze** [comment]
Hallo, ich kann den Fehler bestätigten. bei uns war es genau so. nach dem Update auf 4.0.44 wurden im SW Admin Bereich keine PF Plugin Einstellungen mehr angezeigt. ich werde versuchen die 4.0.45 zu installieren, ob dieses Problem nach wie vor existiert. Ich musste auf 4.0.40 zurückgehen, um ein funktionierendes Bezahlsystem anbieten zu können. Dh, das Problem wurde irgendwo zwischen 4.0.40 und 44 eingebaut.

**Comment by vttn** [comment]
@outamaze @diickens Please update to the latest version of the plugin 4.0.**45**

**Comment by outamaze** [comment]
Ok. it worked with the latest update 4.0.45 again. BUT your latest version is not compatible with the latest Shopware Version.

**Comment by theodorspringwallee** [comment]
@outamaze As I see on our test environment we are compatible with our latest plugin version (4.0.45) and the latest SW6 version (6.4.17.2).

Please can you contact info@wallee.com and tell them the issues, which you receive on our shop?
There we can continue this GitIssue as support case.

Many thanks and best regards
